
IF(WIN32)
    FIND_PROGRAM(MATLAB_MEXEXT mexext.bat)

    GET_FILENAME_COMPONENT(CMAKE_PROGRAM_PATH
        ${MATLAB_MEXEXT} PATH
    )
    FIND_FILE(_MATLAB_PATH "libmat.lib"
        PATH ${CMAKE_PROGRAM_PATH}/../extern/lib/*/microsoft
    )
    GET_FILENAME_COMPONENT(_LIBRARY_PATH
        ${_MATLAB_PATH} PATH
    )

    SET (CMAKE_LIBRARY_PATH ${_LIBRARY_PATH})
    SET (CMAKE_FIND_LIBRARY_PREFIXES "lib")
ELSE(WIN32)
    FIND_PROGRAM(MATLAB_MEXEXT mexext)

    GET_FILENAME_COMPONENT(CMAKE_PROGRAM_PATH
        ${MATLAB_MEXEXT} PATH
    )
    FIND_FILE(_MATLAB_PATH "MATLAB.csf"
        PATH ${CMAKE_PROGRAM_PATH}/*
    )
    GET_FILENAME_COMPONENT(CMAKE_LIBRARY_PATH
        ${_MATLAB_PATH} PATH
    )
ENDIF(WIN32)

FIND_PATH(MATLAB_INCLUDE_DIR
    "mex.h"
    "${CMAKE_PROGRAM_PATH}/../extern/include/"
)

# This is common to UNIX and Win32:

FIND_PROGRAM(MATLAB_MEX_EXECUTABLE
    NAMES mex mex.bat
    NO_CMAKE_ENVIRONMENT_PATH
)
FIND_PROGRAM(MATLAB_MEXEXT_EXECUTABLE
    NAMES mexext mexext.bat
    NO_CMAKE_ENVIRONMENT_PATH
)
FIND_LIBRARY(MATLAB_MEX_LIBRARY
    mex
    NO_CMAKE_ENVIRONMENT_PATH
)
FIND_LIBRARY(MATLAB_MX_LIBRARY
    mx
    NO_CMAKE_ENVIRONMENT_PATH
)
FIND_LIBRARY(MATLAB_MAT_LIBRARY
    mat
    NO_CMAKE_ENVIRONMENT_PATH
)
FIND_LIBRARY(MATLAB_ENG_LIBRARY
    eng
    NO_CMAKE_ENVIRONMENT_PATH
)
FIND_LIBRARY(MATLAB_BLAS_LIBRARY
    mwblas
    NO_CMAKE_ENVIRONMENT_PATH
)
FIND_LIBRARY(MATLAB_LAPACK_LIBRARY
    mwlapack
    NO_CMAKE_ENVIRONMENT_PATH
)

SET(MATLAB_LIBRARIES
    ${MATLAB_MEX_LIBRARY}
    ${MATLAB_MX_LIBRARY}
    ${MATLAB_MAT_LIBRARY}
    ${MATLAB_ENG_LIBRARY}
)

EXECUTE_PROCESS ( COMMAND ${MATLAB_MEXEXT_EXECUTABLE}
        OUTPUT_VARIABLE MATLAB_MEX_EXT
        OUTPUT_STRIP_TRAILING_WHITESPACE
)

# IF(MATLAB_INCLUDE_DIR AND MATLAB_LIBRARIES)
#    MESSAGE(STATUS "Matlab includes:  ${MATLAB_INCLUDE_DIR}")
#    MESSAGE(STATUS "Matlab binaries:  ${CMAKE_PROGRAM_PATH}")
#     MESSAGE(STATUS "Matlab libraries: ${CMAKE_LIBRARY_PATH}")
#     MESSAGE(STATUS "MEX extension: ${MATLAB_MEX_EXT}")
# ENDIF(MATLAB_INCLUDE_DIR AND MATLAB_LIBRARIES)

MARK_AS_ADVANCED(
  MATLAB_LIBRARIES
  MATLAB_MEX_LIBRARY
  MATLAB_MAT_LIBRARY
  MATLAB_MX_LIBRARY
  MATLAB_ENG_LIBRARY
  MATLAB_BLAS_LIBRARY
  MATLAB_LAPACK_LIBRARY
  MATLAB_INCLUDE_DIR
  MATLAB_MEX_EXECUTABLE
  MATLAB_MEXEXT_EXECUTABLE
  MATLAB_MEX_EXT
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Matlab DEFAULT_MSG 
  MATLAB_LIBRARIES
  MATLAB_MEX_LIBRARY
  MATLAB_MAT_LIBRARY
  MATLAB_MX_LIBRARY
  MATLAB_ENG_LIBRARY
  MATLAB_BLAS_LIBRARY
  MATLAB_LAPACK_LIBRARY
  MATLAB_INCLUDE_DIR
  MATLAB_MEX_EXECUTABLE
  MATLAB_MEXEXT_EXECUTABLE
  MATLAB_MEX_EXT
)

