# Create python extensions with swig

find_package(SWIG REQUIRED)

IF (NOT CMAKE_SWIG_OUTDIR)
	SET(CMAKE_SWIG_OUTDIR ${CMAKE_CURRENT_BINARY_DIR})
ENDIF (NOT CMAKE_SWIG_OUTDIR)

MACRO(SWIG_PYTHON_MODULE name file)

	ADD_CUSTOM_COMMAND(
		OUTPUT ${name}_wrap.cxx ${CMAKE_SWIG_OUTDIR}/${name}.py
		COMMAND ${SWIG_EXECUTABLE}	
		ARGS -c++ -python  
			-o ${CMAKE_CURRENT_BINARY_DIR}/${name}_wrap.cxx 
			-outdir ${CMAKE_SWIG_OUTDIR}
			${CMAKE_CURRENT_SOURCE_DIR}/${file}
		DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/${file}
		COMMENT "Swig source")
		
	ADD_LIBRARY(${name} MODULE ${name}_wrap.cxx ${ARGN})

    SET_TARGET_PROPERTIES(${name} PROPERTIES PREFIX "_")
	IF(CMAKE_HOST_WIN32)
		SET_TARGET_PROPERTIES(${name} PROPERTIES SUFFIX ".pyd")
	ENDIF(CMAKE_HOST_WIN32)
	
	GET_TARGET_PROPERTY(FILEPATH ${name} LOCATION)
	ADD_CUSTOM_COMMAND(
		TARGET ${name} POST_BUILD 
		COMMAND ${CMAKE_COMMAND} 
		ARGS -E copy ${FILEPATH} ${CMAKE_SWIG_OUTDIR}
	)

ENDMACRO(SWIG_PYTHON_MODULE)
